### ISSUE TITLE
사용자 이미지가 필요합니다.

### ISSUE THREAD

**Issue by highright96** [TeamHerb/Bookstore-Front#10]
- 내 정보 수정에서 사용자 이미지를 변경할 수 있다. (처음에는 디폴트 이미지)
- 사용자 이미지(판매자)는 중고책 게시글 상세 조회에서 보여준다.

**Comment by sunflower456** [comment]
게시글 상세조회 페이지에 판매자 이미지 및 판매자 이름 보여질 수 있게 조치해놓겠습니다.
