### ISSUE TITLE
판매자 주문 정보에 추가로 필요한 데이터를 요청합니다.

### ISSUE THREAD

**Issue by highright96** [TeamHerb/Bookstore-Front#11]
계좌 정보
- 은행
- 계좌번호
- 예금주

주소
- 수취인 이름
- 주소

가 추가로 필요합니다.

**Comment by GentleDot** [comment]
210905 논의에서 결정된 사안으로
계좌정보 및 주소에 대해 거래 당사자끼리의 채팅을 통한 거래 방식으로 구현함에 따라
정보를 보관하지 않는 방향으로 개발되므로 해당 이슈는 close하도록 하겠습니다.
