### ISSUE TITLE
내 관심목록 요청사항

### ISSUE THREAD

**Issue by highright96** [TeamHerb/Bookstore-Front#16]
![image](https://user-images.githubusercontent.com/55661631/133035510-6a6396e1-aee4-4e32-b1a9-951c9a431d23.png)

내 관심목록에서 판매자와 판매자 이미지를 제외하는건 어떠신가요?

내 관심목록을 보여주기 위해 post - user - image 테이블 모두를 조인하는거는 좋지 않다고 생각 돼서요!

당근을 확인해보니 관심목록에서는 판매자와 판매자 이미지를 보여주지 않네요

**Comment by GentleDot** [comment]
넵, 그러면 관심목록 및 판매글 목록에 이미지는 제거하도록 하겠습니다. :)

**Comment by highright96** [comment]
감사합니다!

**Comment by GentleDot** [comment]
해당 내용 최종 구현 확인 후에 close 할께요.

**Comment by GentleDot** [comment]
![image](https://user-images.githubusercontent.com/15000594/134944441-1cfd7520-7c75-49d4-bd4e-0ceb2584740b.png)

내 관심목록 내 작성자 제거 완료하여 close 하겠습니다.
